libinfluxdb: lib/compat.h File Reference
compat.h File Reference
Functions
void ic_influx_database (char *host, long port, char *db)
void ic_influx_userpw (char *user, char *pw)
void ic_tags (char *tags)
void ic_measure (char *section)
void ic_measureend ()
void ic_sub (char *sub_name)
void ic_subend ()
void ic_long (char *name, long long value)
void ic_double (char *name, double value)
void ic_string (char *name, char *value)
void ic_push ()
void ic_debug (int level)
Function Documentation
ic_debug()
void ic_debug (int level)
Definition at line 71 of file compat.c.
{ debug = level; }
References debug.
ic_double()
void ic_double (char * name, double value)
Definition at line 278 of file compat.c.
{
  ic_check(strlen(name) + 16 + 4);
  if (isnan(value) || isinf(value)) { /* not-a-number or infinity */
    DEBUG fprintf(stderr, "ic_double(%s,%.1f) - nan error\n", name, value);
  } else {
    output_char += sprintf(&output[output_char], "%s=%.3f,", name, value);
    DEBUG fprintf(stderr,
                  "ic_double(\"%s\",%.1f) count=%ld\n",
                  name,
                  value,
                  output_char);
  }
}
References DEBUG, ic_check(), output, and output_char.
Referenced by main().
ic_influx_database()
void ic_influx_database (char * host, long port, char * db)
Definition at line 88 of file compat.c.
{
  struct hostent *he;
  char errorbuf[1024 + 1];
  influx_port = port;
  strncpy(influx_database, db, 256);
  if (host[0] <= '0' && host[0] <= '9') {
    DEBUG fprintf(stderr,
                  "ic_influx(ipaddr=%s,port=%ld,database=%s))\n",
                  host,
                  port,
                  db);
    strncpy(influx_ip, host, 16);
  } else {
    DEBUG fprintf(stderr,
                  "ic_influx_by_hostname(host=%s,port=%ld,database=%s))\n",
                  host,
                  port,
                  db);
    strncpy(influx_hostname, host, 1024);
    if (isalpha(host[0])) {
      he = gethostbyname(host);
      if (he == NULL) {
        sprintf(errorbuf,
                "influx host=%s to ip address convertion failed "
                "gethostbyname(), bailing out\n",
                host);
        error(errorbuf);
      }
      /* this could return multiple ip addresses but we assume its the
       * first one */
      if (he->h_addr_list[0] != NULL) {
        strcpy(influx_ip, inet_ntoa(*(struct in_addr *)(he->h_addr_list[0])));
        DEBUG fprintf(stderr,
                      "ic_influx_by_hostname hostname=%s converted to "
                      "ip address %s))\n",
                      host,
                      influx_ip);
      } else {
        sprintf(errorbuf,
                "influx host=%s to ip address convertion failed (empty "
                "list), bailing out\n",
                host);
        error(errorbuf);
      }
    } else {
      strcpy(influx_ip,
             host); /* perhaps the hostname is actually an ip address */
    }
  }
}
References DEBUG, error(), influx_database, influx_hostname, influx_ip, influx_port, and port.
ic_influx_userpw()
void ic_influx_userpw (char * user, char * pw)
Definition at line 146 of file compat.c.
{
  DEBUG fprintf(stderr,
                "ic_influx_userpw(username=%s,pssword=%s))\n",
                user,
                pw);
  strncpy(influx_username, user, 64);
  strncpy(influx_password, pw, 64);
}
References DEBUG, influx_password, and influx_username.
ic_long()
void ic_long (char * name, long long value)
Definition at line 268 of file compat.c.
{
  ic_check(strlen(name) + 16 + 4);
  output_char += sprintf(&output[output_char], "%s=%lldi,", name, value);
  DEBUG fprintf(stderr,
                "ic_long(\"%s\",%lld) count=%ld\n",
                name,
                value,
                output_char);
}
References DEBUG, ic_check(), output, and output_char.
Referenced by main().
ic_measure()
void ic_measure (char * section)
Definition at line 204 of file compat.c.
{
  ic_check(strlen(section) + strlen(influx_tags) + 3);
  output_char += sprintf(&output[output_char], "%s,%s ", section, influx_tags);
  strcpy(saved_section, section);
  first_sub = 1;
  subended  = 0;
  DEBUG fprintf(stderr, "ic_measure(\"%s\") count=%ld\n", section, output_char);
}
References DEBUG, first_sub, ic_check(), influx_tags, output, output_char, saved_section, and subended.
Referenced by main().
ic_measureend()
void ic_measureend ()
Definition at line 214 of file compat.c.
                     {
  ic_check(4);
  remove_ending_comma_if_any();
  if (!subended) {
    output_char += sprintf(&output[output_char], "   \n");
  }
  subended = 0;
  DEBUG fprintf(stderr, "ic_measureend()\n");
}
References DEBUG, ic_check(), output, output_char, remove_ending_comma_if_any(), and subended.
Referenced by main().
ic_push()
void ic_push ()
Definition at line 309 of file compat.c.
               {
  char header[1024];
  char result[1024];
  char buffer[1024 * 8];
  int ret;
  int i;
  int total;
  int sent;
  int code;
  if (output_char == 0) /* nothing to send so skip this operation */
    return;
  if (influx_port) {
    DEBUG fprintf(stderr, "ic_push() size=%ld\n", output_char);
    if (create_socket() == 1) {
      sprintf(buffer,
              "POST /write?db=%s&u=%s&p=%s HTTP/1.1\r\nHost: "
              "%s:%ld\r\nContent-Length: %ld\r\n\r\n",
              influx_database,
              influx_username,
              influx_password,
              influx_hostname,
              influx_port,
              output_char);
      DEBUG fprintf(stderr,
                    "buffer size=%ld\nbuffer=<%s>\n",
                    strlen(buffer),
                    buffer);
      if ((ret = write(sockfd, buffer, strlen(buffer))) != strlen(buffer)) {
        fprintf(stderr,
                "warning: \"write post to sockfd failed.\" errno=%d\n",
                errno);
      }
      total = output_char;
      sent  = 0;
      if (debug == 2)
        fprintf(stderr, "output size=%d output=\n<%s>\n", total, output);
      while (sent < total) {
        ret = write(sockfd, &output[sent], total - sent);
        DEBUG fprintf(stderr,
                      "written=%d bytes sent=%d total=%d\n",
                      ret,
                      sent,
                      total);
        if (ret < 0) {
          fprintf(stderr,
                  "warning: \"write body to sockfd failed.\" errno=%d\n",
                  errno);
          break;
        }
        sent = sent + ret;
      }
      for (i = 0; i < 1024; i++) /* empty the buffer */
        result[i] = 0;
      if ((ret = read(sockfd, result, sizeof(result))) > 0) {
        result[ret] = 0;
        DEBUG fprintf(stderr, "received bytes=%d data=<%s>\n", ret, result);
        sscanf(result, "HTTP/1.1 %d", &code);
        for (i = 13; i < 1024; i++)
          if (result[i] == '\r')
            result[i] = 0;
        if (debug == 2)
          fprintf(stderr,
                  "http-code=%d text=%s [204=Success]\n",
                  code,
                  &result[13]);
        if (code != 204)
          fprintf(stderr, "code %d -->%s<--\n", code, result);
      }
      close(sockfd);
      sockfd = 0;
      DEBUG fprintf(stderr, "ic_push complete\n");
    } else {
      DEBUG fprintf(stderr, "socket create failed\n");
    }
  } else
    error("influx port is not set, bailing out");
  output[0]   = 0;
  output_char = 0;
}
References create_socket(), DEBUG, debug, error(), influx_database, influx_hostname, influx_password, influx_port, influx_username, output, output_char, and sockfd.
Referenced by main().
ic_string()
void ic_string (char * name, char * value)
Definition at line 292 of file compat.c.
{
  int i;
  int len;
  ic_check(strlen(name) + strlen(value) + 4);
  len = strlen(value);
  for (i = 0; i < len; i++) /* replace problem characters and with a space */
    if (value[i] == '\n' || iscntrl(value[i]))
      value[i] = ' ';
  output_char += sprintf(&output[output_char], "%s=\"%s\",", name, value);
  DEBUG fprintf(stderr,
                "ic_string(\"%s\",\"%s\") count=%ld\n",
                name,
                value,
                output_char);
}
References DEBUG, ic_check(), output, and output_char.
Referenced by main().
ic_sub()
void ic_sub (char * sub_name)
Definition at line 227 of file compat.c.
{
  int i;
  ic_check(strlen(saved_section) + strlen(influx_tags) + strlen(saved_sub) +
           strlen(resource) + 9);
  /* remove previously added section */
  if (first_sub) {
    for (i = output_char - 1; i > 0; i--) {
      if (output[i] == '\n') {
        output[i + 1] = 0;
        output_char   = i + 1;
        break;
      }
    }
  }
  first_sub = 0;
  /* remove the trailing s */
  strcpy(saved_sub, saved_section);
  if (saved_sub[strlen(saved_sub) - 1] == 's') {
    saved_sub[strlen(saved_sub) - 1] = 0;
  }
  output_char += sprintf(&output[output_char],
                         "%s,%s,%s_name=%s ",
                         saved_section,
                         influx_tags,
                         saved_sub,
                         resource);
  subended = 0;
  DEBUG fprintf(stderr, "ic_sub(\"%s\") count=%ld\n", resource, output_char);
}
References DEBUG, first_sub, ic_check(), influx_tags, output, output_char, saved_section, saved_sub, and subended.
Referenced by main().
ic_subend()
void ic_subend ()
Definition at line 260 of file compat.c.
                 {
  ic_check(4);
  remove_ending_comma_if_any();
  output_char += sprintf(&output[output_char], "   \n");
  subended = 1;
  DEBUG fprintf(stderr, "ic_subend()\n");
}
References DEBUG, ic_check(), output, output_char, remove_ending_comma_if_any(), and subended.
Referenced by main().
ic_tags()
void ic_tags (char * tags)
Definition at line 78 of file compat.c.
                      {
  DEBUG fprintf(stderr, "ic_tags(%s)\n", t);
  if (influx_tags == (char *)0) {
    if ((influx_tags = (char *)malloc(MEGABYTE)) == (char *)-1)
      error("failed to malloc() tags buffer");
  }
  strncpy(influx_tags, t, 256);
}
References DEBUG, error(), influx_tags, and MEGABYTE.
Referenced by main().