libinfluxdb: examples/ex1_hello.c File Reference
ex1_hello.c File Reference
#include <libifdb.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 8 of file ex1_hello.c.
{
  int rc = 0;
  // define credentials and info
  char *hostname     = "192.168.86.53";
  uint32_t port      = 8086;
  char *database     = "test_bucket1";
  char *token        = "rtGd3JEQgWFW5rEgCKyNLYIlQCoSu-"
                       "H8bMYE3ejQHI3I2tUbkNIZySWDZVfEuGanvH1ttow9ZBpLbi6EPKquFw==";
  char *organization = "akiel";
  // initialize InfluxDB connection
  InfluxInfo *ifdb_info =
    ifdb_init(token, hostname, organization, port, database);
  if (ifdb_info == NULL) {
    printf("Error initializing InfluxDB\n");
    return -1;
  }
  rc = ifdb_insert(ifdb_info, "measurement_a", "val1=55.5594");
  if (rc != 0) {
    printf("[!] insert #1 failed with rc: %d\n", rc);
    return -1;
  }
  rc = ifdb_insert(ifdb_info, "measurement_a", "val1=45.5598,val2=33.3334");
  if (rc != 0) {
    printf("[!] insert #2 failed with rc: %d\n", rc);
    return -1;
  }
  char start_time[] = "1970-01-01T00:00:00Z";
  char stop_time[]  = "2025-01-03T00:00:00Z";
  //ifdb_delete(ifdb_info, "measurement_a", start_time, stop_time);
  // print the database
  ifdb_show_db(ifdb_info);
  // close connection with the database/bucket
  ifdb_close(ifdb_info);
  return 0;
}
References database, hostname, ifdb_close(), ifdb_init(), ifdb_insert(), ifdb_show_db(), port, and token.