libinfluxdb: lib/utils.h File Reference
utils.h File Reference
Functions
void error (char *buf)
Function Documentation
error()
void error (char * buf)
Definition at line 60 of file compat.c.
                      {
  fprintf(stderr,
          "error: \"%s\" errno=%d meaning=\"%s\"\n",
          buf,
          errno,
          strerror(errno));
  close(sockfd);
  sleep(2); /* this can help the socket close cleanly at the remote end */
  exit(1);
}
References sockfd.
Referenced by create_socket(), create_socket(), ic_check(), ic_influx_database(), ic_push(), ic_push(), ic_tags(), ic_tags(), and main().